export const START_REQUEST_AUTH = 'START_REQUEST_AUTH';
export const REQUEST_LOGIN_SUCCESSFUL = 'REQUEST_LOGIN_SUCCESSFUL';
export const REQUEST_AUTH_FAIL = 'REQUEST_AUTH_FAIL';
export const REQUEST_REGISTR_SUCCESSFUL = 'REQUEST_REGISTR_SUCCESSFUL';