export const PRELOADER_SHOW = 'PRELOADER_SHOW';
export const PRELOADER_HIDE = 'PRELOADER_HIDE';

export const START_REQUEST_CLUSTERS = 'START_REQUEST_CLUSTERS';
export const REQUEST_CLUSTERS_SUCCESSFUL = 'REQUEST_CLUSTERS_SUCCESSFUL';
export const REQUEST_CLUSTERS_FAIL = 'REQUEST_CLUSTERS_FAIL';

export const START_REQUEST_CURRENT_CLUSTER = 'START_REQUEST_CURRENT_CLUSTER';
export const REQUEST_CURRENT_CLUSTER_SUCCESSFUL = 'REQUEST_CURRENT_CLUSTER_SUCCESSFUL';
export const REQUEST_CURRENT_CLUSTER_FAIL = 'REQUEST_CURRENT_CLUSTER_FAIL';

export const COMMAND_SET_POLLING_INTERVAL_START = 'COMMAND_SET_POLLING_INTERVAL_START';
export const COMMAND_SET_POLLING_INTERVAL_SUCCESS = 'COMMAND_SET_POLLING_INTERVAL_SUCCESS';
export const COMMAND_SET_POLLING_INTERVAL_FAIL = 'COMMAND_SET_POLLING_INTERVAL_FAIL';
export const SET_NODE_POLLING_INTERVAL = 'SET_NODE_POLLING_INTERVAL';
export const COMMAND_SET_NODE_STATE_START = 'COMMAND_SET_NODE_STATE_START';
export const COMMAND_SET_NODE_STATE_SUCCESS = 'COMMAND_SET_NODE_STATE_SUCCESS';
export const COMMAND_SET_NODE_STATE_FAIL = 'COMMAND_SET_NODE_STATE_FAIL';
export const SET_NODE_STATE = 'SET_NODE_STATE';
export const NODE_UPDATE_START = 'NODE_UPDATE_START';
export const NODE_UPDATE_SUCCESS = 'NODE_UPDATE_SUCCESS';
export const NODE_UPDATE_FAIL = 'NODE_UPDATE_FAIL';
export const SET_NODE_TITLE = 'SET_NODE_TITLE';

export const SET_CURRENT_NODE = 'SET_CURRENT_NODE';

export const SET_CURRENT_DATA_TYPE = 'SET_CURRENT_DATA_TYPE';
export const SET_PERIOD_FROM = 'SET_PERIOD_FROM';
export const SET_PERIOD_TO = 'SET_PERIOD_TO';
export const PACKS_LOADING_START = 'PACKS_LOADING_START';
export const PACKS_LOADING_SUCCESS = 'PACKS_LOADING_SUCCESS';
export const PACKS_LOADING_FAIL = 'PACKS_LOADING_FAIL';

export const RT_MODE_TOGGLE = 'RT_MODE_TOGGLE';
export const RT_MODE_FETCH_DATA_START = 'RT_MODE_FETCH_DATA_START';
export const RT_MODE_FETCH_DATA_SUCCESSFUL = 'RT_MODE_FETCH_DATA_SUCCESSFUL';
export const RT_MODE_FETCH_DATA_FAIL = 'RT_MODE_FETCH_DATA_FAIL';
